### ISSUE TITLE
Cannot save attribute option

### ISSUE THREAD

**Issue by syssi** [flagbit/akeneo-table-attribute-bundle#28]
PIM Community Edition 2.3.51
Table Attribute Bundle: v2.1.4

Adding a new column at the flagbit table attribute fails:

```
-> POST /configuration/attribute-option/19
-> {"code":"example_code","optionValues":{"de_DE":{"locale":"de_DE","value":"example_translation","id":null}},"constraints":{},"type_config":{},"type":"text"}

<- 400 Bad Request 
<- {"constraints":"This value is not valid.","type_config":"This value is not valid."}
```

**Comment by amansilla** [comment]
This still need to be fixed on the branch `2.X` for support Akeneo `2.3`.

**Comment by amansilla** [comment]
Thx for reporting the issue @syssi. We already released the bugfix for Akeneo `3.0` and now working on integrate it for Akeneo `2.3`. It'll be released really soon.

Please don't forget to 🌟 the repo if you like it!

**Comment by darleenburkhardt** [comment]
PIM Community Edition 3.0.30
Table Attribute Bundle: v3.0.1

Still not working on current PIM Version.

Error: 
`Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO pim_catalog_attribute_option_value (locale_code, value, option_id) VALUES (?, ?, ?)' with params ["en_US", null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'option_id' cannot be null" at /var/www/vhosts/www.domain.tld/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112`

**Comment by amansilla** [comment]
Closed since #31 was merged.
